### ISSUE TITLE
Maintenance takeover request

### ISSUE THREAD

**Issue by KeNaCo** [Michael-F-Bryan/auto-changelog#11]
Hi,
this project is not as active as it can be.
So I think if you won't mind to pass project to other maintainer.
I would be glad to take maintenance of this project, fix bugs and improve it.

**Comment by Michael-F-Bryan** [comment]
I created this ages ago as a little helper program and don't really use it any more. @KeNaCo if you'd like to take over maintenance and continue developing it, I'd be happy to make you a maintainer.

**Comment by KeNaCo** [comment]
Thak you, this is great opportunity for me to start some opensource work :)
