### ISSUE TITLE
New features for incremental changelogs and full CC support

### ISSUE THREAD

**Issue by televi** [Michael-F-Bryan/auto-changelog#12]
I forked your project and added some new features that I was wondering if you'd like merged back.

-a --assume foo - instead of Unreleased, assume the version will be foo
-n --new - only emit new (e.g. Unreleased) changes (will honor the version set by -a)
-b - also emit the body per Conventional Commit standards
-f - also emit the footer per Conventional Commit standards

The use case for the above was "As a developer, I want to be able to generate a brief set of changes to add to my release tag as well as a full set of changes for my change log, all from the conventional commit messages in my git commits".  This was to support using auto-changelog as part of my CI/CD pipeline.

Full changes for CHANGELOG.md release v1.2.3
`auto-changelog -a v1.2.3 -b -f`

Incremental changes (e.g. to merge into an existing changelog where I didn't always use conventional commits):
`cat <(auto-changelog -a v1.2.3 -b -f -n -o /dev/stdout)` CHANGELOG.md > tmp.md && mv tmp.md CHANGELOG.md`

Brief changes for a commit tag for release v1.2.3:
`auto-changelog -a v1.2.3 -n -o /dev/stdout | git tag --file="-" v1.2.3 `

So a simple CI/CD release pipeline would be to do one of the first two, commit that, then do the third.

**Comment by KeNaCo** [comment]
Hi, sorry for late reaction.
I will gladly merge your contribution.

Also if you have some other ideas and want some help, please create issues and we can discuss. I plan to work on this library at least once a week.

**Comment by KeNaCo** [comment]
I start work on CC support by myself. Closing.
