### ISSUE TITLE
Conventional commits: matching scopes only for certain types?

### ISSUE THREAD

**Issue by pranasziaukas** [Michael-F-Bryan/auto-changelog#24]
I'm trying out the tool and it looks pretty nice.

However, I'm a bit confused about the matching of conventional commit message pattern `<type>(<scope>): <subject>`. Why does auto-changelog match scopes only for certain types?

For example, some of my last commit messages may look like this:
* `chore(release): 0.2.0`
* `feat(CLI): ability to select language`
* ...
* `feat: genetic optimisation algorithm`

which results in a changelog

---
#### New Features
- genetic optimisation algorithm
#### Administration and Chores
- [release] 0.2.0
---

So why does it display "[release] 0.2.0" and not "[CLI] ability to select language"?

**Comment by KeNaCo** [comment]
Hi,
this is definitely a bug. Probably parsing regex. I will look at it tomorrow.

**Comment by KeNaCo** [comment]
Ok, bug it is. But with that output, are you using an older version?

**Comment by pranasziaukas** [comment]
I'm using the latest version. But I opened the issue on a phone and did not provide exact commit messages, sorry about that.

Today I see that these commit messages are included in the changelog:
```
feat(CLI): optimize the solution

Use genetic optimization engine to calculate the most accurate payslip.
```
```
feat: genetic optimization engine
```

But these are **not** included
```
fix(CLI): 'gross' or 'net' salary switch
```
```
feat(CLI): ability to choose between net and gross salary values
```
```
feat(CLI): print graphical chart result
```

**Comment by pranasziaukas** [comment]
Still trying to make sense of this.

Tried commiting the following messages before bumping a version
```
docs: usage example
```
```
docs: mathematical concepts behind package
```

And the changelog contains only the first (older) message. Otherwise, there are no special symbols, it's very straightforward.

So maybe the issue is not with parsing rather than with not including all of the commits?

**Comment by KeNaCo** [comment]
The problem is between my chair and the table. I forget to finish all sections in template: **https://github.com/Michael-F-Bryan/auto-changelog/blob/master/auto_changelog/templates/default.jinja2**

**Comment by KeNaCo** [comment]
@pranasziaukas I updated template to hold more sections. I keep it in PR for some time, in case you want to comment or propose some changes.

**Comment by LeMimit** [comment]
Hello !

I am planning to use this amazing little tool to generate changelog.

Is it possible to merge the PR in the master branch ? 
It would be cool to be able to see the previous missing sections supported 👍 

Thanks !
