### ISSUE TITLE
Specify the latest git revison

### ISSUE THREAD

**Issue by WqyJh** [Michael-F-Bryan/auto-changelog#28]
https://github.com/Michael-F-Bryan/auto-changelog/blob/6f5e50a886a3a8902a59536f80982be2a61b87c5/auto_changelog/repository.py#L18

As is shown above, the `auto-changelog` iterates commits from `master` towards the first commit, ignoring the commits hadn't been merged into master branch.

But according to the [git flow](https://nvie.com/posts/a-successful-git-branching-model/), the commits in master branch are in released status, therefore, it could never generate `Unreleased` changelog logically. For projects using git flow, it's better to providing an option to specifying which revision to iterate from.

From my point of view, it's better to iter from the current branch's HEAD, so that every contributors can generate their unreleased contributions and mantainers can generate full changelog during the release process.

**Comment by KeNaCo** [comment]
Hi, thank you for your report.

> As is shown above, the auto-changelog iterates commits from master towards the first commit, ignoring the commits hadn't been merged into master branch.

I put just master to simplify development for me. My vision is to accept any git reference, so you can choose which parts of your git tree you want to include to changelog. As you see, this is not implemented yet.

> But according to the [git flow](https://nvie.com/posts/a-successful-git-branching-model/), the commits in master branch are in released status, therefore, it could never generate Unreleased changelog logically.

I don't agree. Merging to master doesn't imply release. For [git flow](https://nvie.com/posts/a-successful-git-branching-model/) release is defined by tag. So bottom blue commit is merged to master, but not released(_Unreleased_). U can also use release branches, which also can have unreleased stuff.

> For projects using git flow, it's better to providing an option to specifying which revision to iterate from.

I absolutely agree with this. Not implemented yet, see my first comment.

> From my point of view, it's better to iter from the current branch's HEAD, so that every contributors can generate their unreleased contributions and mantainers can generate full changelog during the release process.

This is a really nice idea. Let's implement it.

Last but not least, thank you for MR, I try to look at it in some spare time. Not so much of it tho. Usually, Sunday is my open-source day, so please be patient.

**Comment by WqyJh** [comment]
Well, thank you for your reply!

I agree with what you said. Honestly speaking, I am a little confused about the release process, especially the tagging.

My release process is like this:
1. checkout a `release` branch from `dev` branch
2. bump version
3. test the release branch
4. give the release branch a version tag
5. use `auto-changelog` to generate changelog
6. delete the tag
6. open a merge request to `master` branch
7. merge the MR and tag the `master` branch
8. pull the `master` branch
9. checkout into `dev` branch, merge master branch and push it
10. delete the `release` branch

It's really a complex process and hard to automate.

The step 4 to step 6 is to generate the changelog and include the changelog in the release. The `auto-changelog` tool generate changelog based on tagged version.

For example,
```bash
1c01140 (tag: 0.3.0, master) Merge pull request
608d286 Bump version 0.3.0
51756d9 feat: add 3
266bda7 feat: add 2
f579d0b feat: add 1
```

Before being tagged with `0.3.0`, the `auto-changelog` would put all the changes in `Unreleased` section, only in the later commits it could put the changes in version `0.3.0` section.

Well, I want to keep my changelog and my release version consistent, I can only do things like this,
```bash
6977b64 Generate changelog
608d286 (tag: 0.3.0) Bump version 0.3.0
51756d9 feat: add 3
266bda7 feat: add 2
f579d0b feat: add 1
```
then delete the tag and merge to master, and tag master.
```bash
1c01140 (tag: 0.3.0, master) Merge pull request
6977b64 Generate changelog
608d286 Bump version 0.3.0
51756d9 feat: add 3
266bda7 feat: add 2
f579d0b feat: add 1
```

It's really a bad practice. Would you like to share your release process.
Thank you for your time and patience.

**Comment by KeNaCo** [comment]
Releasing is a pretty complex topic. 
   To get context, we should discuss history. Before git, this was done pretty straight forward. You generate(_manually_) changelog file, and put all your code with the changelog somewhere. Done. Released.
  Git introduces tags, and you can still(_manually_) create changelog and then tag the whole thing as a new release.
  Add auto-generation from git log and here we are. Chicken-egg problem. Changelog should be generated after the tag, but to be part of revision we need to generate it before tag.
  In teams I was involved we discuss different approaches and come to different solutions.

Common solutions, I'm aware of:
1. Don't use a changelog at all.
2. Generate changelog first. Use auto-changelogs option(`-v, --latest-version [version]      # use specified version as latest release`) or update manually. Then add the changelog file to git and tag or use changelog output as an annotated tag message. This will show up nicely as release notes on gitlab/github..
3. Tag and then generate changelog as part of documentation, or update release notes(aka changelog) on gitlab/github/.. via REST API. _I prefer this option when changelog is generated by CI pipeline._

Master and release branches are more about maintenance management than the release process itself.
I'm used to have a master as the main development branch. This means any release in the latest version will be tagged in master. If I need to propagate some changes/fixes to older versions, I create release branches for them(_example: release-1.1.x, release-1.2.x_). Every fix/feature branch can be easily merged to related release branch/master and released.

There is no silver bullet. Every option has pros and cons and can suit different requirements and customs. Have in mind that the process should serve your needs.

**Comment by WqyJh** [comment]
Thank you for your reply, which is really helpful for me. Currently I take solution 2 in my release process. This `auto-changelog` project is really useful, thank you and other contributors.

**Comment by KeNaCo** [comment]
Thank you for contributions :smiley_cat:
