### ISSUE TITLE
simple example doesn't run

### ISSUE THREAD

**Issue by michaelaye** [Michael-F-Bryan/auto-changelog#39]
Watching your simple example video, I tried the examples given there, but nothing happens:

```bash
 auto-changelog --unreleased
Usage: auto-changelog [options]
```
or

```bash
 auto-changelog --latest-version 0.1.6
Usage: auto-changelog [options]
```

I installed auto-changelog via pip, version 0.1.7.

**Comment by KeNaCo** [comment]
My apologies.
I'm aware of this, I updated Readme for 0.3.0, which I planned to release yesterday, but trying to do it in the middle of the night, tired, breaking multiple things in process..

**Comment by KeNaCo** [comment]
0.3.0 released 🎉
