### ISSUE TITLE
Make the module callable from Python script

### ISSUE THREAD

**Issue by masonlouchart** [Michael-F-Bryan/auto-changelog#4]
I would like to use this module from a Python script but I can't access to the `main` function.

I thought write quickly a script that uses [bumpversion](https://github.com/peritus/bumpversion) et follows the [Conventional Commits](conventionalcommits.org) convention to release my project but I'll have to do so using `bash`.

I didn't find anything like this on the Internet. I can't believe it... I have missed it... 🤔

**Comment by jrappen** [comment]
@masonlouchart

<https://github.com/Michael-F-Bryan/auto-changelog#usage>

**Comment by masonlouchart** [comment]
Got it.
