### ISSUE TITLE
Default template of issue url

### ISSUE THREAD

**Issue by LeMimit** [Michael-F-Bryan/auto-changelog#42]
Hello !

I have a proposition concerning the default template of the issue url. 
With the current version we got:

`[#19](https://github.com/Michael-F-Bryan/auto-changelog/issues)`

With this url when we are clicking on the link, we get the home page of the issues of the repo.
I don't think this is really what we are looking for because `#19` is a specific issue that I would like to see by clicking on this link.

From the documentation, we can change this behaviour by using the following parameter
`--issue-url https://github.com/Michael-F-Bryan/auto-changelog/issues/{id}`

And then we get:

`[#19](https://github.com/Michael-F-Bryan/auto-changelog/issues/19)`

This time when we are clicking on the link, we get to see the specific issue (`#19`)

In my opinion, by default we should get by default the `id` at the end of the URL. 
No need to specify a `--issue-url` parameter for that.

The change is quick simple in the function `_issue_from_git_remote_url` we should have:
```python
return urljoin(url + '/', "issues/{id}")
```

I can do a PR to do this change if needed.

Waiting, to have your opinion !

Thanks 👍

**Comment by KeNaCo** [comment]
You're absolutely right, I discovered it today, do the fix and then discover your issue.

One more optimization, `urljoin` is unnecessary.
