### ISSUE TITLE
Version numbers not matching

### ISSUE THREAD

**Issue by masonlouchart** [Michael-F-Bryan/auto-changelog#5]
0.1.6 on [PyPi](https://pypi.python.org/pypi/auto-changelog/0.1.6)

0.1.5 in real life:

<img width="350" alt="capture d ecran 2017-11-16 a 13 11 05" src="https://user-images.githubusercontent.com/2325091/32890953-2513243c-cad1-11e7-9256-50dc2e670148.png">

**Comment by Michael-F-Bryan** [comment]
Fixed in 25a940932d65ada861165100d01c4e7201a65e13 and a new version was uploaded to pypi.
