### ISSUE TITLE
Releases not picked up at all?

### ISSUE THREAD

**Issue by pranasziaukas** [Michael-F-Bryan/auto-changelog#54]
Hi.

I'm following the conventional commits guidelines like
```
git log --oneline

dd8baa9 (HEAD -> master, origin/master) chore(release): 0.3.1
9d04450 fix: move versioning tools to dev dependencies
9925875 chore(release): 0.3.0
e5df24a feat: decompile LUA (using unluac tool)
2805e82 improvement: descriptive CLI progress messages
9394a7c refactor: move unpack functionality to the Cartridge method
a125ff6 chore(release): 0.2.1
e0d3406 feat: semantic versioning tools
fc8e45c feat: unpack GWC to LUAC (+media)
888a821 feat: ByteReader Read bytes of a given file.
f1ed153 feat: a CLI endpoint
32c9347 perf: lock the python dependency versions
8960f27 fix(ci): add poetry to PATH
78b0f0f ci: gitlab pipeline to test and lint
61118a4 improvement: pass tests and lint requirements
cd7b3e1 chore: add licensing
6006543 feat: environment creation routine
8c619cd chore: initial repository outline
```
with tagged release commits `v0.3.1`, etc in between.

However, `auto-changelog` puts everything under one single (latest) release
#### New Features
...

You can find the source code itself at https://gitlab.com/pziaukas/AntiWherigo .

**Comment by KeNaCo** [comment]
Thank you for your report, can you please add also command with options you used? For easy reproduction.

**Comment by pranasziaukas** [comment]
> Thank you for your report, can you please add also command with options you used? For easy reproduction.

No options really, just running `auto-changelog`.

The full workflow is:
```
bump2version minor # create a release commit and tag
auto-changelog
git add CHANGELOG.md
git commit --amend --no-edit
```

**Comment by KeNaCo** [comment]
Ok, sorry for the late answer. Are you marking your releases as tags? Script detects the new release from git tags.

**Comment by pranasziaukas** [comment]
The tags are there @KeNaCo. Are they supposed to be of some specific format?

**Comment by KeNaCo** [comment]
If you check AntiWherigos [graph](https://gitlab.com/pziaukas/AntiWherigo/-/network/master) there is only the master branch but no tags (See auto-changelogs [graph](https://gitlab.com/KeNaCo/auto-changelog-ci-test/-/network/master) for comparison, you can see 0.5.0,0.4.0,...).
Do you have them only on the localhost? In this case are you using simple or annotated tags? 

Just in case link to [git tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

**Comment by stdtom** [comment]
@pranasziaukas  I had a similar issue and option `--tag-prefix v` helped.
Seems like you are using the prefix 'v' as well whereas auto-changelog assumes no prefix per default.

**Comment by pranasziaukas** [comment]
Thanks @stdtom, none of us realized that the `v` prefix was the difference, and there was no `--tag-prefix` flag at the time anyway.
