### ISSUE TITLE
gitpython dependency

### ISSUE THREAD

**Issue by michaelaye** [Michael-F-Bryan/auto-changelog#73]
could the gitpython dependency be updated? conda-forge is at 3.1.x by now, and installing this via pypi clobbers my conda packages by simply removing the conda package and replacing it with the old 2.1.x version.

thanks for your consideration!

**Comment by KeNaCo** [comment]
Hi, thank you for your report.
With the update to 3.1, some work needs to be done, so it will take some time.
When this will be finished, I will release 0.5.0.

**Comment by KeNaCo** [comment]
Ok, just requires reinstall of gitdb and smmap packages.
