### ISSUE TITLE
--debug

### ISSUE THREAD

**Issue by pranasziaukas** [Michael-F-Bryan/auto-changelog#78]
Maybe it would be nice to have some `--debug` flag that prints a more verbose flow of internal information. Would be helpful to know what's going on and debug certain issues.

**Comment by stdtom** [comment]
That would be definitely helpful in some cases.

**Comment by KeNaCo** [comment]
I merged proposed PR. Maybe thoughts for future improvements, so please provide feedback if you can/want.
I imagine three levels of provided information:

- default: warnings+errors in default
- --verbose will provide info following what is done "read git; model builded; composing MD;..."
- --debug will provide debugging with values of variables and even finer tracing of what is happening
