### ISSUE TITLE
BLD: Install with setup.py (pip18)

### ISSUE THREAD

**Issue by emvalbuena** [Michael-F-Bryan/auto-changelog#82]
Hi!

I like the looks of this project. 

I tried to install it with
```bash
git clone https://github.com/Michael-F-Bryan/auto-changelog.git
cd auto-changelog/
pip install .
```
but it didn't work. I realized there is no `setup.py`, because you are using `poetry`. 

My guess is that you don't want to maintain both type of installation procedures, right?

**Comment by stdtom** [comment]
Which pip version do you use?
I cannot reproduce it neither with 19.2.3 nor with 20.2.2.

Your example 
```
git clone https://github.com/Michael-F-Bryan/auto-changelog.git
cd auto-changelog/
pip install .
```
is working as well as
```
pip install git+https://github.com/Michael-F-Bryan/auto-changelog.git
```

See also https://github.com/python-poetry/poetry/issues/321#issuecomment-458205972

**Comment by emvalbuena** [comment]
Oh damn 😂 

I am using pip 18, so that is probably the issue.

Thanks.
